// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/owl.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SignalType is one of the four observability telemetry categories.
// Only LOG is fully implemented in v0.1. The remaining values reserve
// enum space so future plugins never cause a proto schema break.
type SignalType int32

const (
	SignalType_SIGNAL_TYPE_UNSPECIFIED SignalType = 0
	SignalType_SIGNAL_TYPE_LOG         SignalType = 1
	SignalType_SIGNAL_TYPE_METRIC      SignalType = 2
	SignalType_SIGNAL_TYPE_TRACE       SignalType = 3
	SignalType_SIGNAL_TYPE_PROFILE     SignalType = 4
)

// Enum value maps for SignalType.
var (
	SignalType_name = map[int32]string{
		0: "SIGNAL_TYPE_UNSPECIFIED",
		1: "SIGNAL_TYPE_LOG",
		2: "SIGNAL_TYPE_METRIC",
		3: "SIGNAL_TYPE_TRACE",
		4: "SIGNAL_TYPE_PROFILE",
	}
	SignalType_value = map[string]int32{
		"SIGNAL_TYPE_UNSPECIFIED": 0,
		"SIGNAL_TYPE_LOG":         1,
		"SIGNAL_TYPE_METRIC":      2,
		"SIGNAL_TYPE_TRACE":       3,
		"SIGNAL_TYPE_PROFILE":     4,
	}
)

func (x SignalType) Enum() *SignalType {
	p := new(SignalType)
	*p = x
	return p
}

func (x SignalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_owl_proto_enumTypes[0].Descriptor()
}

func (SignalType) Type() protoreflect.EnumType {
	return &file_v1_owl_proto_enumTypes[0]
}

func (x SignalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalType.Descriptor instead.
func (SignalType) EnumDescriptor() ([]byte, []int) {
	return file_v1_owl_proto_rawDescGZIP(), []int{0}
}

// FilterOp defines the comparison operators supported in v0.1.
// Plugins that receive an unsupported op must emulate it in-memory (ADR-0002).
type FilterOp int32

const (
	FilterOp_FILTER_OP_UNSPECIFIED FilterOp = 0
	FilterOp_FILTER_OP_EQ          FilterOp = 1 // field eq value  →  field = value
	FilterOp_FILTER_OP_NE          FilterOp = 2 // field ne value  →  field != value
)

// Enum value maps for FilterOp.
var (
	FilterOp_name = map[int32]string{
		0: "FILTER_OP_UNSPECIFIED",
		1: "FILTER_OP_EQ",
		2: "FILTER_OP_NE",
	}
	FilterOp_value = map[string]int32{
		"FILTER_OP_UNSPECIFIED": 0,
		"FILTER_OP_EQ":          1,
		"FILTER_OP_NE":          2,
	}
)

func (x FilterOp) Enum() *FilterOp {
	p := new(FilterOp)
	*p = x
	return p
}

func (x FilterOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterOp) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_owl_proto_enumTypes[1].Descriptor()
}

func (FilterOp) Type() protoreflect.EnumType {
	return &file_v1_owl_proto_enumTypes[1]
}

func (x FilterOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterOp.Descriptor instead.
func (FilterOp) EnumDescriptor() ([]byte, []int) {
	return file_v1_owl_proto_rawDescGZIP(), []int{1}
}

// Filter is a single OWL filter triplet: field op value.
// Example: level eq error  →  Filter{field:"level", op:EQ, value:"error"}
type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Op            FilterOp               `protobuf:"varint,2,opt,name=op,proto3,enum=openwatchit.v1.FilterOp" json:"op,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_v1_owl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_v1_owl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_v1_owl_proto_rawDescGZIP(), []int{0}
}

func (x *Filter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Filter) GetOp() FilterOp {
	if x != nil {
		return x.Op
	}
	return FilterOp_FILTER_OP_UNSPECIFIED
}

func (x *Filter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// TimeRange expresses a relative lookback window.
// The `last` field uses Go duration strings: "30m", "2h", "7d".
type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Last          string                 `protobuf:"bytes,1,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_v1_owl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_v1_owl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_v1_owl_proto_rawDescGZIP(), []int{1}
}

func (x *TimeRange) GetLast() string {
	if x != nil {
		return x.Last
	}
	return ""
}

// AST is the parsed, structured representation of an OWL query.
// Plugins receive this message — they never parse raw OWL text (ADR-0001).
type AST struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignalType    SignalType             `protobuf:"varint,1,opt,name=signal_type,json=signalType,proto3,enum=openwatchit.v1.SignalType" json:"signal_type,omitempty"`
	Filters       []*Filter              `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	TimeRange     *TimeRange             `protobuf:"bytes,3,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AST) Reset() {
	*x = AST{}
	mi := &file_v1_owl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AST) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AST) ProtoMessage() {}

func (x *AST) ProtoReflect() protoreflect.Message {
	mi := &file_v1_owl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AST.ProtoReflect.Descriptor instead.
func (*AST) Descriptor() ([]byte, []int) {
	return file_v1_owl_proto_rawDescGZIP(), []int{2}
}

func (x *AST) GetSignalType() SignalType {
	if x != nil {
		return x.SignalType
	}
	return SignalType_SIGNAL_TYPE_UNSPECIFIED
}

func (x *AST) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *AST) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *AST) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// BackendConfig carries vendor-agnostic configuration for a single backend.
// Credentials are never stored here; they arrive via environment variables (ADR-0009).
//
// Conventional keys by plugin:
//
//	loki plugin → "url"  e.g. "http://localhost:3100"
type BackendConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Params        map[string]string      `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendConfig) Reset() {
	*x = BackendConfig{}
	mi := &file_v1_owl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendConfig) ProtoMessage() {}

func (x *BackendConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_owl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendConfig.ProtoReflect.Descriptor instead.
func (*BackendConfig) Descriptor() ([]byte, []int) {
	return file_v1_owl_proto_rawDescGZIP(), []int{3}
}

func (x *BackendConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackendConfig) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// ExecuteRequest is the single call the engine makes to run a query.
// The plugin translates the AST to its native language, runs the query,
// normalizes each result row, and streams NormalizedResultRow messages back.
type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ast           *AST                   `protobuf:"bytes,1,opt,name=ast,proto3" json:"ast,omitempty"`
	Config        *BackendConfig         `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_v1_owl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_owl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_v1_owl_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteRequest) GetAst() *AST {
	if x != nil {
		return x.Ast
	}
	return nil
}

func (x *ExecuteRequest) GetConfig() *BackendConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// CapabilitiesRequest is an empty probe sent by the Plugin Manager on startup.
type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_v1_owl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_owl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_v1_owl_proto_rawDescGZIP(), []int{5}
}

// CapabilitiesResponse declares the signal types a plugin handles and its version.
type CapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignalTypes   []SignalType           `protobuf:"varint,1,rep,packed,name=signal_types,json=signalTypes,proto3,enum=openwatchit.v1.SignalType" json:"signal_types,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_v1_owl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_owl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_v1_owl_proto_rawDescGZIP(), []int{6}
}

func (x *CapabilitiesResponse) GetSignalTypes() []SignalType {
	if x != nil {
		return x.SignalTypes
	}
	return nil
}

func (x *CapabilitiesResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// NormalizedResultRow is the common row schema streamed by all plugins.
//
// Canonical fields carry fixed semantics across all vendors — OWL operators
// and cross-signal joins reference these names.
//
// Passthrough carries vendor-specific labels returned with their native names.
// Available to the user but carry no cross-vendor uniformity guarantee.
type NormalizedResultRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonical fields
	TimestampNs int64  `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"` // Unix nanoseconds
	Source      string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`                               // vendor identifier, e.g. "loki"
	Level       string `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`                                 // severity: error, warn, info, debug
	Service     string `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`                             // service or app name
	Message     string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                             // log line or event description
	TraceId     string `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`              // distributed trace identifier
	SpanId      string `protobuf:"bytes,7,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`                 // span within the trace
	// Vendor-specific fields — no cross-vendor uniformity guarantee
	Passthrough   map[string]string `protobuf:"bytes,8,rep,name=passthrough,proto3" json:"passthrough,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizedResultRow) Reset() {
	*x = NormalizedResultRow{}
	mi := &file_v1_owl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizedResultRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedResultRow) ProtoMessage() {}

func (x *NormalizedResultRow) ProtoReflect() protoreflect.Message {
	mi := &file_v1_owl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedResultRow.ProtoReflect.Descriptor instead.
func (*NormalizedResultRow) Descriptor() ([]byte, []int) {
	return file_v1_owl_proto_rawDescGZIP(), []int{7}
}

func (x *NormalizedResultRow) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *NormalizedResultRow) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *NormalizedResultRow) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *NormalizedResultRow) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *NormalizedResultRow) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NormalizedResultRow) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *NormalizedResultRow) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *NormalizedResultRow) GetPassthrough() map[string]string {
	if x != nil {
		return x.Passthrough
	}
	return nil
}

var File_v1_owl_proto protoreflect.FileDescriptor

const file_v1_owl_proto_rawDesc = "" +
	"\n" +
	"\fv1/owl.proto\x12\x0eopenwatchit.v1\"^\n" +
	"\x06Filter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12(\n" +
	"\x02op\x18\x02 \x01(\x0e2\x18.openwatchit.v1.FilterOpR\x02op\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\x1f\n" +
	"\tTimeRange\x12\x12\n" +
	"\x04last\x18\x01 \x01(\tR\x04last\"\xc4\x01\n" +
	"\x03AST\x12;\n" +
	"\vsignal_type\x18\x01 \x01(\x0e2\x1a.openwatchit.v1.SignalTypeR\n" +
	"signalType\x120\n" +
	"\afilters\x18\x02 \x03(\v2\x16.openwatchit.v1.FilterR\afilters\x128\n" +
	"\n" +
	"time_range\x18\x03 \x01(\v2\x19.openwatchit.v1.TimeRangeR\ttimeRange\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xa1\x01\n" +
	"\rBackendConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12A\n" +
	"\x06params\x18\x02 \x03(\v2).openwatchit.v1.BackendConfig.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\x0eExecuteRequest\x12%\n" +
	"\x03ast\x18\x01 \x01(\v2\x13.openwatchit.v1.ASTR\x03ast\x125\n" +
	"\x06config\x18\x02 \x01(\v2\x1d.openwatchit.v1.BackendConfigR\x06config\"\x15\n" +
	"\x13CapabilitiesRequest\"o\n" +
	"\x14CapabilitiesResponse\x12=\n" +
	"\fsignal_types\x18\x01 \x03(\x0e2\x1a.openwatchit.v1.SignalTypeR\vsignalTypes\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xe6\x02\n" +
	"\x13NormalizedResultRow\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x03R\vtimestampNs\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\a \x01(\tR\x06spanId\x12V\n" +
	"\vpassthrough\x18\b \x03(\v24.openwatchit.v1.NormalizedResultRow.PassthroughEntryR\vpassthrough\x1a>\n" +
	"\x10PassthroughEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x86\x01\n" +
	"\n" +
	"SignalType\x12\x1b\n" +
	"\x17SIGNAL_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSIGNAL_TYPE_LOG\x10\x01\x12\x16\n" +
	"\x12SIGNAL_TYPE_METRIC\x10\x02\x12\x15\n" +
	"\x11SIGNAL_TYPE_TRACE\x10\x03\x12\x17\n" +
	"\x13SIGNAL_TYPE_PROFILE\x10\x04*I\n" +
	"\bFilterOp\x12\x19\n" +
	"\x15FILTER_OP_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fFILTER_OP_EQ\x10\x01\x12\x10\n" +
	"\fFILTER_OP_NE\x10\x022\xbc\x01\n" +
	"\rPluginService\x12Y\n" +
	"\fCapabilities\x12#.openwatchit.v1.CapabilitiesRequest\x1a$.openwatchit.v1.CapabilitiesResponse\x12P\n" +
	"\aExecute\x12\x1e.openwatchit.v1.ExecuteRequest\x1a#.openwatchit.v1.NormalizedResultRow0\x01B0Z.github.com/elyosemite/openwatchit/api/v1;apiv1b\x06proto3"

var (
	file_v1_owl_proto_rawDescOnce sync.Once
	file_v1_owl_proto_rawDescData []byte
)

func file_v1_owl_proto_rawDescGZIP() []byte {
	file_v1_owl_proto_rawDescOnce.Do(func() {
		file_v1_owl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_owl_proto_rawDesc), len(file_v1_owl_proto_rawDesc)))
	})
	return file_v1_owl_proto_rawDescData
}

var file_v1_owl_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_owl_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_owl_proto_goTypes = []any{
	(SignalType)(0),              // 0: openwatchit.v1.SignalType
	(FilterOp)(0),                // 1: openwatchit.v1.FilterOp
	(*Filter)(nil),               // 2: openwatchit.v1.Filter
	(*TimeRange)(nil),            // 3: openwatchit.v1.TimeRange
	(*AST)(nil),                  // 4: openwatchit.v1.AST
	(*BackendConfig)(nil),        // 5: openwatchit.v1.BackendConfig
	(*ExecuteRequest)(nil),       // 6: openwatchit.v1.ExecuteRequest
	(*CapabilitiesRequest)(nil),  // 7: openwatchit.v1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil), // 8: openwatchit.v1.CapabilitiesResponse
	(*NormalizedResultRow)(nil),  // 9: openwatchit.v1.NormalizedResultRow
	nil,                          // 10: openwatchit.v1.BackendConfig.ParamsEntry
	nil,                          // 11: openwatchit.v1.NormalizedResultRow.PassthroughEntry
}
var file_v1_owl_proto_depIdxs = []int32{
	1,  // 0: openwatchit.v1.Filter.op:type_name -> openwatchit.v1.FilterOp
	0,  // 1: openwatchit.v1.AST.signal_type:type_name -> openwatchit.v1.SignalType
	2,  // 2: openwatchit.v1.AST.filters:type_name -> openwatchit.v1.Filter
	3,  // 3: openwatchit.v1.AST.time_range:type_name -> openwatchit.v1.TimeRange
	10, // 4: openwatchit.v1.BackendConfig.params:type_name -> openwatchit.v1.BackendConfig.ParamsEntry
	4,  // 5: openwatchit.v1.ExecuteRequest.ast:type_name -> openwatchit.v1.AST
	5,  // 6: openwatchit.v1.ExecuteRequest.config:type_name -> openwatchit.v1.BackendConfig
	0,  // 7: openwatchit.v1.CapabilitiesResponse.signal_types:type_name -> openwatchit.v1.SignalType
	11, // 8: openwatchit.v1.NormalizedResultRow.passthrough:type_name -> openwatchit.v1.NormalizedResultRow.PassthroughEntry
	7,  // 9: openwatchit.v1.PluginService.Capabilities:input_type -> openwatchit.v1.CapabilitiesRequest
	6,  // 10: openwatchit.v1.PluginService.Execute:input_type -> openwatchit.v1.ExecuteRequest
	8,  // 11: openwatchit.v1.PluginService.Capabilities:output_type -> openwatchit.v1.CapabilitiesResponse
	9,  // 12: openwatchit.v1.PluginService.Execute:output_type -> openwatchit.v1.NormalizedResultRow
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_v1_owl_proto_init() }
func file_v1_owl_proto_init() {
	if File_v1_owl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_owl_proto_rawDesc), len(file_v1_owl_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_owl_proto_goTypes,
		DependencyIndexes: file_v1_owl_proto_depIdxs,
		EnumInfos:         file_v1_owl_proto_enumTypes,
		MessageInfos:      file_v1_owl_proto_msgTypes,
	}.Build()
	File_v1_owl_proto = out.File
	file_v1_owl_proto_goTypes = nil
	file_v1_owl_proto_depIdxs = nil
}
